dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  # - "3.8-dev" -- pandas won't build
  # - "nightly" -- pandas won't build
install:
  - pip install -e .
  - pip install -r dev-requirements.txt
script:
  - python -m flake8 ./laforge
  - python -m pylint ./laforge
  - laforge --version
